### ISSUE TITLE
Could you also share the weight of the pretrained decoder?

### ISSUE THREAD

**Issue by hongxin001** [ariG23498/mae-scalable-vision-learners#15]
Hi,

Thanks for your excellent implementation! I found that you have shared the weights of the encoder, but if we want to replicate the reconstruction, the pretrained decoder is still needed. So, could you also share the weight of the pretrained decoder? 

Best Regards,
Hongxin

**Comment by sayakpaul** [comment]
Thanks for reaching out. 

Unfortunately, we didn't serialize the decoder because reconstruction wasn't our main objective with this project. I think it's relatively cheap to train MAE on Colab. Maybe you could run our code and get the decoder from there?
