### ISSUE TITLE
Final layer in decoder is incorrect

### ISSUE THREAD

**Issue by LucasYoung** [ariG23498/mae-scalable-vision-learners#18]
Excuse me if this is my mistake.

The final layer of the decoder, pre_final, flattens all of the patches into a 1D vector and then uses a Dense layer that maps the features to the entire image size.

This differs from the official PyTorch implementation (https://github.com/facebookresearch/mae/blob/efb2a8062c206524e35e47d04501ed4f544c0ae8/models_mae.py#L58) where for each token, the key is mapped to the patch size.

This makes a huge difference in the efficiency of the network, because this pre_final Dense layer is enormous.

**Comment by ariG23498** [comment]
Hey @LucasYoung 

I think https://github.com/ariG23498/mae-scalable-vision-learners/issues/17 covers the same issue. I have mentioned the problem in more details there. Thank you for your interest in the work!

**Comment by LucasYoung** [comment]
Thank you. Closing due to duplicate.
